### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [dava/dava.engine#83]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/dava/dava.framework/blob/43e11c2874400deb8603594a5006820e04b7719c/Tools/UIEditor/Classes/main.cpp#L6 "main function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www-h.eng.cam.ac.uk/help/importedHTML/languages/C++/Thinking_in_C++/tic0255.html#Heading680 "Uncaught exceptions") like they are described by Bruce Eckel?

**Comment by binaryzebra** [comment]
Performance is not an issue with C++11, C++14. We use exceptions only in the parts of the code related to filesystem, so we do not plan to put catch in main. 

At the same time everyone who want to protect their code and want to use exceptions can put try / catch in GameMain, and enclose the whole game into try / catch.

**Comment by elfring** [comment]
Would you like to [reconsider consequences from implementation-defined behaviour](https://stackoverflow.com/questions/5557555/raii-and-stack-unwinding "RAII and Stack unwinding")?

**Comment by binaryzebra** [comment]
Engine itself it very stable, we have more than 99% crash-free users on all platforms (including Android with more than 10k different devices) in quite big MMO game that is developed on the engine. 

Could you explain why do you think it's so important?

**Comment by elfring** [comment]
* How do you think about to look at the referenced information sources once more?
* On which implementation-defined behaviour would you like to depend on in your software applications?

**Comment by binaryzebra** [comment]
I went through all of them. 
Catching of the exceptions on top level, leads to catching all problems and missing them. In our case it means that we should capture everything, and do something with those exceptions. 

Either we should develop own method of sending crashes and faults to us, or we should rely on services like Fabric.io(Crashlytics) or Hocker.app. Those services catch all crashes and send them to us. 

We do not see reasons why we should catch everything in main, avoiding crashes and problems, instead of getting the crashes in Crashlytics and fixing them. For the user there is no difference, exception is failure and crash is the same type of failure. 

So we believe that exceptions should be handled manually by the game developer. If you want to use Crashlytics, or Hockey.app you'll be able to use them, because engine is not forcing you to something. At the same time you can do that yourself.
